### ISSUE TITLE
unset host/port causing errors on js console from apiman

### ISSUE THREAD

**Issue by gashcrumb** [fabric8io/fabric8-console#10]
CC @EricWittmann

Seeing:

```
XMLHttpRequest cannot load http://%3Cno%20value%3E:<no%20value>/apiman/system/status. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.e @ libs-f4d3f866.js:7x @ libs-f4d3f866.js:7$get.c @ libs-f4d3f866.js:7l @ libs-f4d3f866.js:8(anonymous function) @ libs-f4d3f866.js:8$get.h.$eval @ libs-f4d3f866.js:8$get.h.$digest @ libs-f4d3f866.js:8$get.h.$apply @ libs-f4d3f866.js:8(anonymous function) @ libs-f4d3f866.js:18(anonymous function) @ libs-f4d3f866.js:18t.on @ libs-f4d3f866.js:18(anonymous function) @ mainPlugin.ts:61r @ libs-f4d3f866.js:5(anonymous function) @ libs-f4d3f866.js:5a @ libs-f4d3f866.js:5He @ libs-f4d3f866.js:5s @ libs-f4d3f866.js:5Z @ libs-f4d3f866.js:5(anonymous function) @ libs-f4d3f866.js:13e.loadPlugins.e.registerPreBootstrapTask.task @ libs-f4d3f866.js:11e.loadPlugins.a @ libs-f4d3f866.js:11(anonymous function) @ libs-f4d3f866.js:107e.loadPlugins.a @ libs-f4d3f866.js:11(anonymous function) @ libs-f4d3f866.js:106e.loadPlugins.a @ libs-f4d3f866.js:11r @ libs-f4d3f866.js:79(anonymous function) @ libs-f4d3f866.js:79Z.Callbacks.u @ libs-f4d3f866.js:3Z.Callbacks.d.fireWith @ libs-f4d3f866.js:3n @ libs-f4d3f866.js:5Z.ajaxTransport.Y.cors.e.crossDomain.send.t @ libs-f4d3f866.js:5
libs-f4d3f866.js:8 Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://%3Cno%20value%3E:<no%20value>/apiman/system/status'.
    at Error (native)
    at e (http://fabric8.demo.fabric8.io/libs-f4d3f866.js:7:24100)
    at x (http://fabric8.demo.fabric8.io/libs-f4d3f866.js:7:22222)
    at $get.c (http://fabric8.demo.fabric8.io/libs-f4d3f866.js:7:20721)
    at l (http://fabric8.demo.fabric8.io/libs-f4d3f866.js:8:5888)
    at http://fabric8.demo.fabric8.io/libs-f4d3f866.js:8:6060
    at h.$get.h.$eval (http://fabric8.demo.fabric8.io/libs-f4d3f866.js:8:13452)
    at h.$get.h.$digest (http://fabric8.demo.fabric8.io/libs-f4d3f866.js:8:11961)
    at h.$get.h.$apply (http://fabric8.demo.fabric8.io/libs-f4d3f866.js:8:13719)
    at http://fabric8.demo.fabric8.io/libs-f4d3f866.js:18:27747(anonymous function) @ libs-f4d3f866.js:8$get @ libs-f4d3f866.js:7l @ libs-f4d3f866.js:8(anonymous function) @ libs-f4d3f866.js:8$get.h.$eval @ libs-f4d3f866.js:8$get.h.$digest @ libs-f4d3f866.js:8$get.h.$apply @ libs-f4d3f866.js:8(anonymous function) @ libs-f4d3f866.js:18(anonymous function) @ libs-f4d3f866.js:18t.on @ libs-f4d3f866.js:18(anonymous function) @ mainPlugin.ts:61r @ libs-f4d3f866.js:5(anonymous function) @ libs-f4d3f866.js:5a @ libs-f4d3f866.js:5He @ libs-f4d3f866.js:5s @ libs-f4d3f866.js:5Z @ libs-f4d3f866.js:5(anonymous function) @ libs-f4d3f866.js:13e.loadPlugins.e.registerPreBootstrapTask.task @ libs-f4d3f866.js:11e.loadPlugins.a @ libs-f4d3f866.js:11(anonymous function) @ libs-f4d3f866.js:107e.loadPlugins.a @ libs-f4d3f866.js:11(anonymous function) @ libs-f4d3f866.js:106e.loadPlugins.a @ libs-f4d3f866.js:11r @ libs-f4d3f866.js:79(anonymous function) @ libs-f4d3f866.js:79Z.Callbacks.u @ libs-f4d3f866.js:3Z.Callbacks.d.fireWith @ libs-f4d3f866.js:3n @ libs-f4d3f866.js:5Z.ajaxTransport.Y.cors.e.crossDomain.send.t @ libs-f4d3f866.js:5
libs-f4d3f866.js:11 [api-manager] Error getting apiman system status: {"stack":"Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://%3Cno%20value%3E:<no%20value>/apiman/system/status'.\n    at Error (native)\n    at e (http://fabric8.demo.fabric8.io/libs-f4d3f866.js:7:24100)\n    at x (http://fabric8.demo.fabric8.io/libs-f4d3f866.js:7:22222)\n    at $get.c (http://fabric8.demo.fabric8.io/libs-f4d3f866.js:7:20721)\n    at l (http://fabric8.demo.fabric8.io/libs-f4d3f866.js:8:5888)\n    at http://fabric8.demo.fabric8.io/libs-f4d3f866.js:8:6060\n    at h.$get.h.$eval (http://fabric8.demo.fabric8.io/libs-f4d3f866.js:8:13452)\n    at h.$get.h.$digest (http://fabric8.demo.fabric8.io/libs-f4d3f866.js:8:11961)\n    at h.$get.h.$apply (http://fabric8.demo.fabric8.io/libs-f4d3f866.js:8:13719)\n    at http://fabric8.demo.fabric8.io/libs-f4d3f866.js:18:27747"}
```

Note the URL being queried -> ```http://%3Cno%20value%3E:<no%20value>/apiman/system/status```

Also we've recently introduced pre-bootstrap task dependencies, might be good if an oauth token is required by the frontend to add a task dependency on hawtio-oauth, kind of like (we do here)[https://github.com/hawtio/hawtio-kubernetes/blob/master/plugins/kubernetes/ts/watcher.ts#L43-66] like on line 45.

**Comment by EricWittmann** [comment]
@KurtStam Any thoughts on this?

@gashcrumb Did something change recently that would break this?  I thought it was working OK...

**Comment by robtaireeo** [comment]
Getting the same result, running OO v3 natively:

```javascript
Failed to load resource: the server responded with a status of 403 (Forbidden)
libs-375df221.js:11 [kubernetes-watcher] error :  Forbidden
libs-375df221.js:7 XMLHttpRequest cannot load http://%3Cno%20value%3E:<no%20value>/apiman/system/status. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.(anonymous function) @ libs-375df221.js:7
libs-375df221.js:8 Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://%3Cno%20value%3E:<no%20value>/apiman/system/status'.
    at Error (native)
    at http://fabric8.ares.home/libs-375df221.js:7:24100
    at x (http://fabric8.ares.home/libs-375df221.js:7:22222)
    at c (http://fabric8.ares.home/libs-375df221.js:7:20721)
    at l (http://fabric8.ares.home/libs-375df221.js:8:5888)
    at http://fabric8.ares.home/libs-375df221.js:8:6060
    at h.$eval (http://fabric8.ares.home/libs-375df221.js:8:13452)
    at h.$digest (http://fabric8.ares.home/libs-375df221.js:8:11961)
    at h.$apply (http://fabric8.ares.home/libs-375df221.js:8:13719)
    at http://fabric8.ares.home/libs-375df221.js:18:27779(anonymous function) @ libs-375df221.js:8
```

**Comment by gashcrumb** [comment]
non-issue now
