### ISSUE TITLE
codemirror regression on minishift

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-console#250]
if you create a project then navigate to Source you get:
```
libs.js:71238ReferenceError: CodeMirror is not defined
    at http://192.168.64.176:30175/libs-9850d5e6.js:57:5880
    at Object.i [as createEditorSettings] (http://192.168.64.176:30175/libs-9850d5e6.js:57:6226)
    at new <anonymous> (http://192.168.64.176:30175/app-4be1b5bd.js:5:19824)
    at Object.a [as invoke] (http://192.168.64.176:30175/libs-9850d5e6.js:26:20491)
    at c.instance (http://192.168.64.176:30175/libs-9850d5e6.js:27:14848)
    at h (http://192.168.64.176:30175/libs-9850d5e6.js:27:1695)
    at a (http://192.168.64.176:30175/libs-9850d5e6.js:26:30229)
    at http://192.168.64.176:30175/libs-9850d5e6.js:26:29760
    at Object.link (http://192.168.64.176:30175/libs-9850d5e6.js:40:12271)
    at http://192.168.64.176:30175/libs-9850d5e6.js:26:4899 <div class="row kubernetes-view ng-scope" ng-view="">
```

**Comment by gashcrumb** [comment]
Something's up with the codemirror dependency, I've locked it at 5.17.0 for now, will need to do some further investigation and ultimately fix it in hawtio-ui.

**Comment by jstrachan** [comment]
@gashcrumb many thanks!!!
