### ISSUE TITLE
events.js unhandled error

### ISSUE THREAD

**Issue by mynameismevin** [fabric8io/fabric8-console#67]
When following the [clone and build](http://fabric8.io/guide/getStarted/gke.html) instructions, I am receiving this error at the `gulp site` step:

```javascript
[15:32:19] site files libs/nvd3/build/nv.d3.js
[15:32:19] site files 334 items
[15:32:19] Finished 'site-files' after 626 ms
[15:32:19] Starting 'usemin'...
[15:32:19] Starting 'write-version-json'...
[15:32:19] Finished 'write-version-json' after 3.99 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
ReferenceError: Promise is not defined
    at /home/lloydm/Development/Repositories/fabric8-console/node_modules/gulp-usemin/lib/htmlBuilder.js:38:16
    at Array.map (native)
    at module.exports (/home/lloydm/Development/Repositories/fabric8-console/node_modules/gulp-usemin/lib/htmlBuilder.js:37:25)
    at Transform._transform (/home/lloydm/Development/Repositories/fabric8-console/node_modules/gulp-usemin/index.js:17:9)
    at Transform._read (/home/lloydm/Development/Repositories/fabric8-console/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/home/lloydm/Development/Repositories/fabric8-console/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/lloydm/Development/Repositories/fabric8-console/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/lloydm/Development/Repositories/fabric8-console/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/home/lloydm/Development/Repositories/fabric8-console/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/home/lloydm/Development/Repositories/fabric8-console/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
```

How can I resolve this?

**Comment by mynameismevin** [comment]
The issue was related to a bad NodeJS installation. Once I built NodeJS from source, it worked just fine.
